// verifier_impl.rs - STARK proof verification for the Satsu Merkle membership proof
//
// This module provides Rust-side verification of STARK proofs generated by the MembershipProver.
// It wraps Winterfell's `verify` function with the appropriate type parameters.

use winterfell::{
    crypto::{hashers::Blake3_256, DefaultRandomCoin, MerkleTree},
    math::fields::f128::BaseElement,
    AcceptableOptions, Proof,
};

use crate::air::MembershipAir;
use crate::types::SatsuPublicInputs;

/// Verify a STARK proof for the Satsu Merkle membership statement.
///
/// This function checks that the proof is valid for the given public inputs:
/// - The prover knew a commitment (leaf) in the Merkle tree with the given root
/// - The commitment is correctly formed from secret + nullifier
/// - The nullifier hash matches the public nullifier hash
/// - The recipient and relayer fee are bound to the proof
///
/// Returns `Ok(())` if the proof is valid, or `Err(String)` with a description of the failure.
pub fn verify_membership_proof(
    proof: Proof,
    pub_inputs: SatsuPublicInputs,
) -> Result<(), String> {
    // Accept proofs with any conjectured security level for testing.
    // In production, use MinConjecturedSecurity(95) or higher.
    let acceptable = AcceptableOptions::MinConjecturedSecurity(0);

    winterfell::verify::<
        MembershipAir,
        Blake3_256<BaseElement>,
        DefaultRandomCoin<Blake3_256<BaseElement>>,
        MerkleTree<Blake3_256<BaseElement>>,
    >(proof, pub_inputs, &acceptable)
    .map_err(|e| format!("STARK verification failed: {e}"))
}

/// Verify a STARK proof from serialized bytes.
///
/// This is useful for verifying proofs that have been transmitted over the network.
pub fn verify_proof_from_bytes(
    proof_bytes: &[u8],
    pub_inputs: SatsuPublicInputs,
) -> Result<(), String> {
    let proof = Proof::from_bytes(proof_bytes)
        .map_err(|e| format!("Failed to deserialize proof: {e}"))?;

    verify_membership_proof(proof, pub_inputs)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::rescue::rescue_hash;
    use winterfell::math::fields::f128::BaseElement;
    use winterfell::math::FieldElement;

    /// Helper to create test public/private inputs with a valid Merkle tree.
    /// Uses leaf_index=5 (binary 101) to ensure mixed path bits.
    fn make_test_pub_inputs() -> (SatsuPublicInputs, crate::types::SatsuPrivateInputs) {
        let secret = BaseElement::new(0xDEADBEEF);
        let nullifier = BaseElement::new(0xCAFEBABE);
        let commitment = rescue_hash(secret, nullifier);

        let depth = 4;
        let leaf_index = 5usize;
        let num_leaves = 1 << depth;
        let mut leaves = Vec::with_capacity(num_leaves);
        for i in 0..num_leaves {
            if i == leaf_index {
                leaves.push(commitment);
            } else {
                leaves.push(rescue_hash(
                    BaseElement::new(i as u128),
                    BaseElement::new(i as u128),
                ));
            }
        }

        let mut tree: Vec<Vec<BaseElement>> = Vec::new();
        tree.push(leaves);

        for level in 0..depth {
            let prev = &tree[level];
            let mut next_level = Vec::new();
            for pair in prev.chunks(2) {
                next_level.push(rescue_hash(pair[0], pair[1]));
            }
            tree.push(next_level);
        }

        let root = tree[depth][0];

        let mut merkle_path = Vec::new();
        let mut path_indices = Vec::new();
        let mut index = leaf_index;

        for level in 0..depth {
            let sibling_index = if index % 2 == 0 { index + 1 } else { index - 1 };
            merkle_path.push(tree[level][sibling_index]);
            path_indices.push(if index % 2 == 0 {
                BaseElement::ZERO
            } else {
                BaseElement::ONE
            });
            index /= 2;
        }

        let nullifier_hash = rescue_hash(nullifier, BaseElement::ZERO);
        let recipient_hash = BaseElement::new(0x1234);
        let relayer_fee = BaseElement::new(0);

        let pub_inputs = SatsuPublicInputs {
            commitment,
            nullifier_hash,
            root,
            recipient_hash,
            relayer_fee,
        };

        let priv_inputs = crate::types::SatsuPrivateInputs {
            commitment,
            merkle_path,
            path_indices,
        };

        (pub_inputs, priv_inputs)
    }

    #[test]
    fn test_verification_with_wrong_root_fails() {
        use crate::prover_impl::MembershipProver;
        use winterfell::{FieldExtension, ProofOptions, Prover};

        let (pub_inputs, priv_inputs) = make_test_pub_inputs();

        let options = ProofOptions::new(1, 2, 0, FieldExtension::None, 2, 1);
        let prover = MembershipProver::new(options, pub_inputs.clone());
        let trace = prover.build_trace(&priv_inputs);
        let proof = prover.prove(trace).expect("proof generation should succeed");

        // Modify the root in public inputs
        let mut bad_pub_inputs = pub_inputs;
        bad_pub_inputs.root = BaseElement::new(0xBADBADBAD);

        let result = verify_membership_proof(proof, bad_pub_inputs);
        assert!(result.is_err(), "verification should fail with wrong root");
    }

    #[test]
    fn test_verification_with_wrong_commitment_fails() {
        use crate::prover_impl::MembershipProver;
        use winterfell::{FieldExtension, ProofOptions, Prover};

        let (pub_inputs, priv_inputs) = make_test_pub_inputs();

        let options = ProofOptions::new(1, 2, 0, FieldExtension::None, 2, 1);
        let prover = MembershipProver::new(options, pub_inputs.clone());
        let trace = prover.build_trace(&priv_inputs);
        let proof = prover.prove(trace).expect("proof generation should succeed");

        // Modify the commitment in public inputs
        let mut bad_pub_inputs = pub_inputs;
        bad_pub_inputs.commitment = BaseElement::new(0xBADBADBAD);

        let result = verify_membership_proof(proof, bad_pub_inputs);
        assert!(
            result.is_err(),
            "verification should fail with wrong commitment"
        );
    }

    #[test]
    fn test_proof_serialization_roundtrip() {
        use crate::prover_impl::MembershipProver;
        use winterfell::{FieldExtension, ProofOptions, Prover};

        let (pub_inputs, priv_inputs) = make_test_pub_inputs();

        let options = ProofOptions::new(1, 2, 0, FieldExtension::None, 2, 1);
        let prover = MembershipProver::new(options, pub_inputs.clone());
        let trace = prover.build_trace(&priv_inputs);
        let proof = prover.prove(trace).expect("proof generation should succeed");

        // Serialize and deserialize
        let bytes = proof.to_bytes();
        assert!(!bytes.is_empty(), "serialized proof should not be empty");

        // Verify from bytes
        let result = verify_proof_from_bytes(&bytes, pub_inputs);
        assert!(
            result.is_ok(),
            "verification from bytes should succeed: {:?}",
            result.err()
        );
    }
}
